version: '3.8'
services:
  db_test:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marble_test
    ports:
      - "5433:5432"  # Different port from development DB
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]  # Log all SQL for debugging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
