[package]
name = "marble-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Storage backends for Marble"

[dependencies]
marble-core.workspace = true
marble-db.workspace = true
# Dependencies will be added as needed
